# https://github.com/pypa/manylinux?tab=readme-ov-file#manylinux_2_34-almalinux-9-based---alpha
# manylinux_2_34 (AlmaLinux 9 based) - ALPHA
#
# This image is used for building portable binary wheels for linux. It doesn't contain any
# dependencies for building document or running tests.
#
# Build the image:
#   docker build . -f ./dev/Dockerfile.manylinux_2_34 -t pyhwloc-manylinux_2_34:latest
#
# Build the wheel:
#   docker run --rm --gpus=all --workdir=/ws --mount type=bind,src=.,dst=/ws cuda-13-manylinux:latest -- python -m pip wheel -v . --config-settings=fetch-hwloc=True --wheel-dir dist/
#
# Audit the wheel:
#   docker run --rm --gpus=all --workdir=/ws --mount type=bind,src=.,dst=/ws cuda-13-manylinux:latest -- auditwheel repair --only-plat --plat ${WHEEL_TAG} ./dist/*.whl


FROM nvcr.io/nvidia/cuda:13.0.1-devel-rockylinux9
ARG TARGETPLATFORM

RUN \
    dnf update -y

RUN \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --set-enabled devel && \
    dnf install cmake python3-pip git ninja-build wget -y && \
    dnf install autoconf automake libtool libpciaccess-devel -y && \
    rm -rf /var/cache/dnf

RUN \
    case $TARGETPLATFORM in \
        linux/amd64) \
            wget -nv -O miniforge3.sh https://github.com/conda-forge/miniforge/releases/download/25.11.0-1/Miniforge3-25.11.0-1-Linux-x86_64.sh \
            ;; \
        linux/arm64) \
            wget -nv -O miniforge3.sh https://github.com/conda-forge/miniforge/releases/download/25.11.0-1/Miniforge3-25.11.0-1-Linux-aarch64.sh \
            ;; \
        *) \
	    exit -1 \
	    ;; \
    esac

RUN \
    bash miniforge3.sh -b -p /opt/miniforge

ENV PATH="$PATH:/opt/miniforge/bin"

RUN mamba install hatchling auditwheel patchelf -y
