name: Build and test manylinux_2_34 wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    uses: ./.github/workflows/manylinux-image.yml

  test-wheel:
    uses: ./.github/workflows/manylinux-wheel.yml
