name: Build and test manylinux_2_34 wheels

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    uses: ./.github/workflows/manylinux-image.yml

  test-wheel:
    uses: ./.github/workflows/manylinux-wheel.yml
